# mPaaS Pods Begin
plugin "cocoapods-mPaaS"
source "https://code.aliyun.com/mpaas-public/podspecs.git"
source 'https://github.com/CocoaPods/Specs.git'
mPaaS_baseline '10.1.32'  # 请将 x.x.x 替换成真实基线版本
mPaaS_version_code 18   # This line is maintained by MPaaS plugin automatically. Please don't modify.

target 'podTest' do
  use_frameworks!
  
  mPaaS_pod "mPaaS_Nebula" 
#  pod 'FackTalkLib', :git => 'https://github.com/sunianVV/FackTalkLib.git'
#  pod 'AFNetworking'
#  pod 'Tools', :git => 'https://github.com/sunianVV/Tools.git'
end
